# alacritty config
---
# Font configuration
font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

  size: 18.0
# End Font configuration

# Shell configuration
shell:
  program: /Users/mdvis/.local/bin/tmux
# End Shell configuration
